services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    env_file:
      - .env
      - .build.env
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
  database:
    image: postgres:16-alpine
    env_file:
      - .build.env
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "dspoken", "-U", "dspoken"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5434:5432"
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data:rw
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
volumes:
  caddy_data:
  caddy_config:
  pgadmin:
