App\Infrastructure\Entity\Analysis\Visit:
  operations:
    ApiPlatform\Metadata\GetCollection: ~
    ApiPlatform\Metadata\Get: ~
    ApiPlatform\Metadata\Post: ~
    ApiPlatform\Metadata\Put: ~
    ApiPlatform\Metadata\Patch: ~