<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240623084128 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE analysis_visit_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE common_app_file_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE core_language_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE core_location_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE core_question_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE core_question_version_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE core_quiz_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE core_quiz_version_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE core_reference_language_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE core_response_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE core_response_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE member_ship_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE member_ship_user_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE member_ship_user_profile_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE message_contact_message_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_article_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_article_version_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_default_report_version_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_language_article_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_language_web_link_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_language_youtube_link_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_report_section_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_report_section_version_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_web_link_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_youtube_link_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE security_role_object_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE security_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE security_user_role_object_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE subscription_subscription_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tag_tag_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tag_tag_version_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE analysis_visit (id INT NOT NULL, code VARCHAR(255) NOT NULL, session_id VARCHAR(255) NOT NULL, user_code VARCHAR(255) DEFAULT NULL, token VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7497618C77153098 ON analysis_visit (code)');
        $this->addSql('CREATE TABLE common_app_file (id INT NOT NULL, code VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, section VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EC81D42777153098 ON common_app_file (code)');
        $this->addSql('CREATE TABLE core_language (id INT NOT NULL, creator_id INT DEFAULT NULL, app_file_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, code VARCHAR(255) NOT NULL, score INT DEFAULT 0 NOT NULL, description TEXT DEFAULT NULL, country_code VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, people VARCHAR(255) DEFAULT NULL, is_published BOOLEAN DEFAULT false NOT NULL, display_weight INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6B19071661220EA6 ON core_language (creator_id)');
        $this->addSql('CREATE INDEX IDX_6B1907167E96F921 ON core_language (app_file_id)');
        $this->addSql('CREATE TABLE core_location (id INT NOT NULL, language_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, label VARCHAR(255) DEFAULT NULL, country_code VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, people VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, extended_length DOUBLE PRECISION DEFAULT NULL, raduis INT DEFAULT NULL, circumstances TEXT DEFAULT NULL, is_main BOOLEAN NOT NULL, display_weight INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E15CFF6882F1BAF4 ON core_location (language_id)');
        $this->addSql('CREATE INDEX IDX_E15CFF6861220EA6 ON core_location (creator_id)');
        $this->addSql('CREATE TABLE core_question (id INT NOT NULL, quiz_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, default_label VARCHAR(255) DEFAULT NULL, question_type_code VARCHAR(255) DEFAULT NULL, enabled BOOLEAN DEFAULT NULL, is_published BOOLEAN DEFAULT false NOT NULL, display_weight INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9353FED77153098 ON core_question (code)');
        $this->addSql('CREATE INDEX IDX_9353FED853CD175 ON core_question (quiz_id)');
        $this->addSql('CREATE INDEX IDX_9353FED61220EA6 ON core_question (creator_id)');
        $this->addSql('CREATE TABLE core_question_version (id INT NOT NULL, question_id INT NOT NULL, reference_language_id INT NOT NULL, creator_id INT DEFAULT NULL, code VARCHAR(64) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D40D23DA1E27F6BF ON core_question_version (question_id)');
        $this->addSql('CREATE INDEX IDX_D40D23DA64C6F8C0 ON core_question_version (reference_language_id)');
        $this->addSql('CREATE INDEX IDX_D40D23DA61220EA6 ON core_question_version (creator_id)');
        $this->addSql('CREATE UNIQUE INDEX question_version_unique ON core_question_version (question_id, reference_language_id)');
        $this->addSql('CREATE TABLE core_quiz (id INT NOT NULL, app_file_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, label VARCHAR(255) DEFAULT NULL, score INT DEFAULT 0 NOT NULL, description TEXT DEFAULT NULL, enabled BOOLEAN NOT NULL, is_default BOOLEAN NOT NULL, is_published BOOLEAN DEFAULT false NOT NULL, display_weight INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_96F739A777153098 ON core_quiz (code)');
        $this->addSql('CREATE INDEX IDX_96F739A77E96F921 ON core_quiz (app_file_id)');
        $this->addSql('CREATE TABLE core_quiz_version (id INT NOT NULL, quiz_id INT NOT NULL, reference_language_id INT NOT NULL, creator_id INT DEFAULT NULL, code VARCHAR(64) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F6C7BB853CD175 ON core_quiz_version (quiz_id)');
        $this->addSql('CREATE INDEX IDX_F6C7BB64C6F8C0 ON core_quiz_version (reference_language_id)');
        $this->addSql('CREATE INDEX IDX_F6C7BB61220EA6 ON core_quiz_version (creator_id)');
        $this->addSql('CREATE UNIQUE INDEX quiz_version_unique ON core_quiz_version (quiz_id, reference_language_id)');
        $this->addSql('CREATE TABLE core_reference_language (id INT NOT NULL, code VARCHAR(5) NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, enabled BOOLEAN DEFAULT NULL, is_default BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23B95E4477153098 ON core_reference_language (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23B95E44EA750E8 ON core_reference_language (label)');
        $this->addSql('CREATE TABLE core_response (id INT NOT NULL, question_id INT DEFAULT NULL, response_group_id INT DEFAULT NULL, answer VARCHAR(255) DEFAULT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_81B97D581E27F6BF ON core_response (question_id)');
        $this->addSql('CREATE INDEX IDX_81B97D5849423F3A ON core_response (response_group_id)');
        $this->addSql('CREATE UNIQUE INDEX question_response_group_unique ON core_response (question_id, response_group_id)');
        $this->addSql('CREATE TABLE core_response_group (id INT NOT NULL, quiz_id INT NOT NULL, language_id INT NOT NULL, user_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_86EA761A77153098 ON core_response_group (code)');
        $this->addSql('CREATE INDEX IDX_86EA761A853CD175 ON core_response_group (quiz_id)');
        $this->addSql('CREATE INDEX IDX_86EA761A82F1BAF4 ON core_response_group (language_id)');
        $this->addSql('CREATE INDEX IDX_86EA761AA76ED395 ON core_response_group (user_id)');
        $this->addSql('CREATE TABLE member_ship_group (id INT NOT NULL, code TEXT DEFAULT NULL, default_label TEXT DEFAULT NULL, default_description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE member_ship_user_group (id INT NOT NULL, user_id INT DEFAULT NULL, group_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7188289A76ED395 ON member_ship_user_group (user_id)');
        $this->addSql('CREATE INDEX IDX_7188289FE54D947 ON member_ship_user_group (group_id)');
        $this->addSql('CREATE TABLE member_ship_user_profile (id INT NOT NULL, code VARCHAR(255) NOT NULL, public_username VARCHAR(255) NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, birthdate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, origin_country_code VARCHAR(255) DEFAULT NULL, living_country_code VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE message_contact_message (id INT NOT NULL, sender_id INT DEFAULT NULL, recipient_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, type VARCHAR(255) NOT NULL, waiting_for_answer BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_54CB4F0877153098 ON message_contact_message (code)');
        $this->addSql('CREATE INDEX IDX_54CB4F08F624B39D ON message_contact_message (sender_id)');
        $this->addSql('CREATE INDEX IDX_54CB4F08E92F8F78 ON message_contact_message (recipient_id)');
        $this->addSql('CREATE TABLE report_article (id INT NOT NULL, default_title VARCHAR(64) DEFAULT NULL, default_description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, is_published BOOLEAN DEFAULT false NOT NULL, code VARCHAR(64) DEFAULT NULL, template_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE report_article_version (id INT NOT NULL, reference_language_id INT DEFAULT NULL, article_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, code VARCHAR(64) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7C2A165964C6F8C0 ON report_article_version (reference_language_id)');
        $this->addSql('CREATE INDEX IDX_7C2A16597294869C ON report_article_version (article_id)');
        $this->addSql('CREATE TABLE report_default_report_version (id INT NOT NULL, reference_language_id INT DEFAULT NULL, web_link_id INT DEFAULT NULL, youtube_link_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, code VARCHAR(64) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BD32E8B264C6F8C0 ON report_default_report_version (reference_language_id)');
        $this->addSql('CREATE INDEX IDX_BD32E8B2450BACEF ON report_default_report_version (web_link_id)');
        $this->addSql('CREATE INDEX IDX_BD32E8B2D7E5295 ON report_default_report_version (youtube_link_id)');
        $this->addSql('CREATE TABLE report_language_article (id INT NOT NULL, language_id INT DEFAULT NULL, article_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E30661C682F1BAF4 ON report_language_article (language_id)');
        $this->addSql('CREATE INDEX IDX_E30661C67294869C ON report_language_article (article_id)');
        $this->addSql('CREATE TABLE report_language_web_link (id INT NOT NULL, language_id INT DEFAULT NULL, web_link_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_24990B8382F1BAF4 ON report_language_web_link (language_id)');
        $this->addSql('CREATE INDEX IDX_24990B83450BACEF ON report_language_web_link (web_link_id)');
        $this->addSql('CREATE TABLE report_language_youtube_link (id INT NOT NULL, language_id INT DEFAULT NULL, youtube_link_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C848274D82F1BAF4 ON report_language_youtube_link (language_id)');
        $this->addSql('CREATE INDEX IDX_C848274DD7E5295 ON report_language_youtube_link (youtube_link_id)');
        $this->addSql('CREATE TABLE report_report_section (id INT NOT NULL, article_id INT DEFAULT NULL, default_title VARCHAR(255) NOT NULL, default_content TEXT DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, template_code VARCHAR(255) DEFAULT NULL, position INT NOT NULL, code VARCHAR(64) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1D66AB927294869C ON report_report_section (article_id)');
        $this->addSql('CREATE TABLE report_report_section_version (id INT NOT NULL, report_section_id INT DEFAULT NULL, reference_language_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, content TEXT DEFAULT NULL, code VARCHAR(64) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A580B9D2CB61CF41 ON report_report_section_version (report_section_id)');
        $this->addSql('CREATE INDEX IDX_A580B9D264C6F8C0 ON report_report_section_version (reference_language_id)');
        $this->addSql('CREATE TABLE report_web_link (id INT NOT NULL, article_id INT DEFAULT NULL, default_title VARCHAR(64) DEFAULT NULL, default_description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, is_published BOOLEAN DEFAULT false NOT NULL, code VARCHAR(64) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F2CE0D797294869C ON report_web_link (article_id)');
        $this->addSql('CREATE TABLE report_youtube_link (id INT NOT NULL, article_id INT DEFAULT NULL, default_title VARCHAR(64) DEFAULT NULL, default_description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, is_published BOOLEAN DEFAULT false NOT NULL, code VARCHAR(64) DEFAULT NULL, video_link VARCHAR(255) DEFAULT NULL, channel_link VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF54114E7294869C ON report_youtube_link (article_id)');
        $this->addSql('CREATE TABLE security_role_object (id INT NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23241D3CEA750E8 ON security_role_object (label)');
        $this->addSql('CREATE TABLE security_user (id INT NOT NULL, code VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, enable_confirmation_token VARCHAR(255) DEFAULT NULL, reset_password_token VARCHAR(255) DEFAULT NULL, api_token VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52825A8877153098 ON security_user (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52825A88F85E0677 ON security_user (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52825A88E7927C74 ON security_user (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52825A881C209556 ON security_user (enable_confirmation_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52825A88452C9EC5 ON security_user (reset_password_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52825A887BA2F5EB ON security_user (api_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52825A88C05FB297 ON security_user (confirmation_token)');
        $this->addSql('COMMENT ON COLUMN security_user.roles IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE security_user_role_object (id INT NOT NULL, role_object_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1FB8D4D172D985F7 ON security_user_role_object (role_object_id)');
        $this->addSql('CREATE INDEX IDX_1FB8D4D1A76ED395 ON security_user_role_object (user_id)');
        $this->addSql('CREATE TABLE subscription_subscription (id INT NOT NULL, approved_by_id INT DEFAULT NULL, subscriber_id INT DEFAULT NULL, language_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, request_message TEXT DEFAULT NULL, response_message TEXT DEFAULT NULL, accepted BOOLEAN NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, approved BOOLEAN NOT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, approve_message TEXT DEFAULT NULL, for_owner BOOLEAN NOT NULL, for_viewer BOOLEAN NOT NULL, for_editor BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CD90784477153098 ON subscription_subscription (code)');
        $this->addSql('CREATE INDEX IDX_CD9078442D234F6A ON subscription_subscription (approved_by_id)');
        $this->addSql('CREATE INDEX IDX_CD9078447808B1AD ON subscription_subscription (subscriber_id)');
        $this->addSql('CREATE INDEX IDX_CD90784482F1BAF4 ON subscription_subscription (language_id)');
        $this->addSql('CREATE UNIQUE INDEX language_subscriber_unique ON subscription_subscription (language_id, subscriber_id)');
        $this->addSql('CREATE TABLE tag_tag (id INT NOT NULL, code VARCHAR(64) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tag_tag_version (id INT NOT NULL, reference_language_id INT NOT NULL, code VARCHAR(64) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_91E4848964C6F8C0 ON tag_tag_version (reference_language_id)');
        $this->addSql('ALTER TABLE core_language ADD CONSTRAINT FK_6B19071661220EA6 FOREIGN KEY (creator_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_language ADD CONSTRAINT FK_6B1907167E96F921 FOREIGN KEY (app_file_id) REFERENCES common_app_file (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_location ADD CONSTRAINT FK_E15CFF6882F1BAF4 FOREIGN KEY (language_id) REFERENCES core_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_location ADD CONSTRAINT FK_E15CFF6861220EA6 FOREIGN KEY (creator_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_question ADD CONSTRAINT FK_9353FED853CD175 FOREIGN KEY (quiz_id) REFERENCES core_quiz (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_question ADD CONSTRAINT FK_9353FED61220EA6 FOREIGN KEY (creator_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_question_version ADD CONSTRAINT FK_D40D23DA1E27F6BF FOREIGN KEY (question_id) REFERENCES core_question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_question_version ADD CONSTRAINT FK_D40D23DA64C6F8C0 FOREIGN KEY (reference_language_id) REFERENCES core_reference_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_question_version ADD CONSTRAINT FK_D40D23DA61220EA6 FOREIGN KEY (creator_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_quiz ADD CONSTRAINT FK_96F739A77E96F921 FOREIGN KEY (app_file_id) REFERENCES common_app_file (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_quiz_version ADD CONSTRAINT FK_F6C7BB853CD175 FOREIGN KEY (quiz_id) REFERENCES core_quiz (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_quiz_version ADD CONSTRAINT FK_F6C7BB64C6F8C0 FOREIGN KEY (reference_language_id) REFERENCES core_reference_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_quiz_version ADD CONSTRAINT FK_F6C7BB61220EA6 FOREIGN KEY (creator_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_response ADD CONSTRAINT FK_81B97D581E27F6BF FOREIGN KEY (question_id) REFERENCES core_question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_response ADD CONSTRAINT FK_81B97D5849423F3A FOREIGN KEY (response_group_id) REFERENCES core_response_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_response_group ADD CONSTRAINT FK_86EA761A853CD175 FOREIGN KEY (quiz_id) REFERENCES core_quiz (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_response_group ADD CONSTRAINT FK_86EA761A82F1BAF4 FOREIGN KEY (language_id) REFERENCES core_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE core_response_group ADD CONSTRAINT FK_86EA761AA76ED395 FOREIGN KEY (user_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE member_ship_user_group ADD CONSTRAINT FK_7188289A76ED395 FOREIGN KEY (user_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE member_ship_user_group ADD CONSTRAINT FK_7188289FE54D947 FOREIGN KEY (group_id) REFERENCES member_ship_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message_contact_message ADD CONSTRAINT FK_54CB4F08F624B39D FOREIGN KEY (sender_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message_contact_message ADD CONSTRAINT FK_54CB4F08E92F8F78 FOREIGN KEY (recipient_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_article_version ADD CONSTRAINT FK_7C2A165964C6F8C0 FOREIGN KEY (reference_language_id) REFERENCES core_reference_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_article_version ADD CONSTRAINT FK_7C2A16597294869C FOREIGN KEY (article_id) REFERENCES report_article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_default_report_version ADD CONSTRAINT FK_BD32E8B264C6F8C0 FOREIGN KEY (reference_language_id) REFERENCES core_reference_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_default_report_version ADD CONSTRAINT FK_BD32E8B2450BACEF FOREIGN KEY (web_link_id) REFERENCES report_web_link (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_default_report_version ADD CONSTRAINT FK_BD32E8B2D7E5295 FOREIGN KEY (youtube_link_id) REFERENCES report_youtube_link (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_language_article ADD CONSTRAINT FK_E30661C682F1BAF4 FOREIGN KEY (language_id) REFERENCES core_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_language_article ADD CONSTRAINT FK_E30661C67294869C FOREIGN KEY (article_id) REFERENCES report_article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_language_web_link ADD CONSTRAINT FK_24990B8382F1BAF4 FOREIGN KEY (language_id) REFERENCES core_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_language_web_link ADD CONSTRAINT FK_24990B83450BACEF FOREIGN KEY (web_link_id) REFERENCES report_web_link (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_language_youtube_link ADD CONSTRAINT FK_C848274D82F1BAF4 FOREIGN KEY (language_id) REFERENCES core_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_language_youtube_link ADD CONSTRAINT FK_C848274DD7E5295 FOREIGN KEY (youtube_link_id) REFERENCES report_youtube_link (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_report_section ADD CONSTRAINT FK_1D66AB927294869C FOREIGN KEY (article_id) REFERENCES report_article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_report_section_version ADD CONSTRAINT FK_A580B9D2CB61CF41 FOREIGN KEY (report_section_id) REFERENCES report_report_section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_report_section_version ADD CONSTRAINT FK_A580B9D264C6F8C0 FOREIGN KEY (reference_language_id) REFERENCES core_reference_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_web_link ADD CONSTRAINT FK_F2CE0D797294869C FOREIGN KEY (article_id) REFERENCES report_article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_youtube_link ADD CONSTRAINT FK_BF54114E7294869C FOREIGN KEY (article_id) REFERENCES report_article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE security_user_role_object ADD CONSTRAINT FK_1FB8D4D172D985F7 FOREIGN KEY (role_object_id) REFERENCES security_role_object (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE security_user_role_object ADD CONSTRAINT FK_1FB8D4D1A76ED395 FOREIGN KEY (user_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_subscription ADD CONSTRAINT FK_CD9078442D234F6A FOREIGN KEY (approved_by_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_subscription ADD CONSTRAINT FK_CD9078447808B1AD FOREIGN KEY (subscriber_id) REFERENCES security_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_subscription ADD CONSTRAINT FK_CD90784482F1BAF4 FOREIGN KEY (language_id) REFERENCES core_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tag_tag_version ADD CONSTRAINT FK_91E4848964C6F8C0 FOREIGN KEY (reference_language_id) REFERENCES core_reference_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE analysis_visit_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE common_app_file_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE core_language_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE core_location_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE core_question_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE core_question_version_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE core_quiz_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE core_quiz_version_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE core_reference_language_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE core_response_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE core_response_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE member_ship_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE member_ship_user_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE member_ship_user_profile_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE message_contact_message_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_article_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_article_version_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_default_report_version_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_language_article_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_language_web_link_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_language_youtube_link_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_report_section_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_report_section_version_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_web_link_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_youtube_link_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE security_role_object_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE security_user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE security_user_role_object_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE subscription_subscription_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tag_tag_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tag_tag_version_id_seq CASCADE');
        $this->addSql('ALTER TABLE core_language DROP CONSTRAINT FK_6B19071661220EA6');
        $this->addSql('ALTER TABLE core_language DROP CONSTRAINT FK_6B1907167E96F921');
        $this->addSql('ALTER TABLE core_location DROP CONSTRAINT FK_E15CFF6882F1BAF4');
        $this->addSql('ALTER TABLE core_location DROP CONSTRAINT FK_E15CFF6861220EA6');
        $this->addSql('ALTER TABLE core_question DROP CONSTRAINT FK_9353FED853CD175');
        $this->addSql('ALTER TABLE core_question DROP CONSTRAINT FK_9353FED61220EA6');
        $this->addSql('ALTER TABLE core_question_version DROP CONSTRAINT FK_D40D23DA1E27F6BF');
        $this->addSql('ALTER TABLE core_question_version DROP CONSTRAINT FK_D40D23DA64C6F8C0');
        $this->addSql('ALTER TABLE core_question_version DROP CONSTRAINT FK_D40D23DA61220EA6');
        $this->addSql('ALTER TABLE core_quiz DROP CONSTRAINT FK_96F739A77E96F921');
        $this->addSql('ALTER TABLE core_quiz_version DROP CONSTRAINT FK_F6C7BB853CD175');
        $this->addSql('ALTER TABLE core_quiz_version DROP CONSTRAINT FK_F6C7BB64C6F8C0');
        $this->addSql('ALTER TABLE core_quiz_version DROP CONSTRAINT FK_F6C7BB61220EA6');
        $this->addSql('ALTER TABLE core_response DROP CONSTRAINT FK_81B97D581E27F6BF');
        $this->addSql('ALTER TABLE core_response DROP CONSTRAINT FK_81B97D5849423F3A');
        $this->addSql('ALTER TABLE core_response_group DROP CONSTRAINT FK_86EA761A853CD175');
        $this->addSql('ALTER TABLE core_response_group DROP CONSTRAINT FK_86EA761A82F1BAF4');
        $this->addSql('ALTER TABLE core_response_group DROP CONSTRAINT FK_86EA761AA76ED395');
        $this->addSql('ALTER TABLE member_ship_user_group DROP CONSTRAINT FK_7188289A76ED395');
        $this->addSql('ALTER TABLE member_ship_user_group DROP CONSTRAINT FK_7188289FE54D947');
        $this->addSql('ALTER TABLE message_contact_message DROP CONSTRAINT FK_54CB4F08F624B39D');
        $this->addSql('ALTER TABLE message_contact_message DROP CONSTRAINT FK_54CB4F08E92F8F78');
        $this->addSql('ALTER TABLE report_article_version DROP CONSTRAINT FK_7C2A165964C6F8C0');
        $this->addSql('ALTER TABLE report_article_version DROP CONSTRAINT FK_7C2A16597294869C');
        $this->addSql('ALTER TABLE report_default_report_version DROP CONSTRAINT FK_BD32E8B264C6F8C0');
        $this->addSql('ALTER TABLE report_default_report_version DROP CONSTRAINT FK_BD32E8B2450BACEF');
        $this->addSql('ALTER TABLE report_default_report_version DROP CONSTRAINT FK_BD32E8B2D7E5295');
        $this->addSql('ALTER TABLE report_language_article DROP CONSTRAINT FK_E30661C682F1BAF4');
        $this->addSql('ALTER TABLE report_language_article DROP CONSTRAINT FK_E30661C67294869C');
        $this->addSql('ALTER TABLE report_language_web_link DROP CONSTRAINT FK_24990B8382F1BAF4');
        $this->addSql('ALTER TABLE report_language_web_link DROP CONSTRAINT FK_24990B83450BACEF');
        $this->addSql('ALTER TABLE report_language_youtube_link DROP CONSTRAINT FK_C848274D82F1BAF4');
        $this->addSql('ALTER TABLE report_language_youtube_link DROP CONSTRAINT FK_C848274DD7E5295');
        $this->addSql('ALTER TABLE report_report_section DROP CONSTRAINT FK_1D66AB927294869C');
        $this->addSql('ALTER TABLE report_report_section_version DROP CONSTRAINT FK_A580B9D2CB61CF41');
        $this->addSql('ALTER TABLE report_report_section_version DROP CONSTRAINT FK_A580B9D264C6F8C0');
        $this->addSql('ALTER TABLE report_web_link DROP CONSTRAINT FK_F2CE0D797294869C');
        $this->addSql('ALTER TABLE report_youtube_link DROP CONSTRAINT FK_BF54114E7294869C');
        $this->addSql('ALTER TABLE security_user_role_object DROP CONSTRAINT FK_1FB8D4D172D985F7');
        $this->addSql('ALTER TABLE security_user_role_object DROP CONSTRAINT FK_1FB8D4D1A76ED395');
        $this->addSql('ALTER TABLE subscription_subscription DROP CONSTRAINT FK_CD9078442D234F6A');
        $this->addSql('ALTER TABLE subscription_subscription DROP CONSTRAINT FK_CD9078447808B1AD');
        $this->addSql('ALTER TABLE subscription_subscription DROP CONSTRAINT FK_CD90784482F1BAF4');
        $this->addSql('ALTER TABLE tag_tag_version DROP CONSTRAINT FK_91E4848964C6F8C0');
        $this->addSql('DROP TABLE analysis_visit');
        $this->addSql('DROP TABLE common_app_file');
        $this->addSql('DROP TABLE core_language');
        $this->addSql('DROP TABLE core_location');
        $this->addSql('DROP TABLE core_question');
        $this->addSql('DROP TABLE core_question_version');
        $this->addSql('DROP TABLE core_quiz');
        $this->addSql('DROP TABLE core_quiz_version');
        $this->addSql('DROP TABLE core_reference_language');
        $this->addSql('DROP TABLE core_response');
        $this->addSql('DROP TABLE core_response_group');
        $this->addSql('DROP TABLE member_ship_group');
        $this->addSql('DROP TABLE member_ship_user_group');
        $this->addSql('DROP TABLE member_ship_user_profile');
        $this->addSql('DROP TABLE message_contact_message');
        $this->addSql('DROP TABLE report_article');
        $this->addSql('DROP TABLE report_article_version');
        $this->addSql('DROP TABLE report_default_report_version');
        $this->addSql('DROP TABLE report_language_article');
        $this->addSql('DROP TABLE report_language_web_link');
        $this->addSql('DROP TABLE report_language_youtube_link');
        $this->addSql('DROP TABLE report_report_section');
        $this->addSql('DROP TABLE report_report_section_version');
        $this->addSql('DROP TABLE report_web_link');
        $this->addSql('DROP TABLE report_youtube_link');
        $this->addSql('DROP TABLE security_role_object');
        $this->addSql('DROP TABLE security_user');
        $this->addSql('DROP TABLE security_user_role_object');
        $this->addSql('DROP TABLE subscription_subscription');
        $this->addSql('DROP TABLE tag_tag');
        $this->addSql('DROP TABLE tag_tag_version');
    }
}
